// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/keyboard_message.proto

package psm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyboardType_KeyboardLayout int32

const (
	KeyboardType_UNKNOWN KeyboardType_KeyboardLayout = 0
	KeyboardType_QWERTY  KeyboardType_KeyboardLayout = 1
	KeyboardType_QWERTZ  KeyboardType_KeyboardLayout = 2
	KeyboardType_AZERTY  KeyboardType_KeyboardLayout = 3
)

// Enum value maps for KeyboardType_KeyboardLayout.
var (
	KeyboardType_KeyboardLayout_name = map[int32]string{
		0: "UNKNOWN",
		1: "QWERTY",
		2: "QWERTZ",
		3: "AZERTY",
	}
	KeyboardType_KeyboardLayout_value = map[string]int32{
		"UNKNOWN": 0,
		"QWERTY":  1,
		"QWERTZ":  2,
		"AZERTY":  3,
	}
)

func (x KeyboardType_KeyboardLayout) Enum() *KeyboardType_KeyboardLayout {
	p := new(KeyboardType_KeyboardLayout)
	*p = x
	return p
}

func (x KeyboardType_KeyboardLayout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyboardType_KeyboardLayout) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_keyboard_message_proto_enumTypes[0].Descriptor()
}

func (KeyboardType_KeyboardLayout) Type() protoreflect.EnumType {
	return &file_proto_keyboard_message_proto_enumTypes[0]
}

func (x KeyboardType_KeyboardLayout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyboardType_KeyboardLayout.Descriptor instead.
func (KeyboardType_KeyboardLayout) EnumDescriptor() ([]byte, []int) {
	return file_proto_keyboard_message_proto_rawDescGZIP(), []int{0, 0}
}

type KeyboardType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout  KeyboardType_KeyboardLayout `protobuf:"varint,1,opt,name=layout,proto3,enum=process_manager.KeyboardType_KeyboardLayout" json:"layout,omitempty"`
	Backlit bool                        `protobuf:"varint,2,opt,name=backlit,proto3" json:"backlit,omitempty"`
}

func (x *KeyboardType) Reset() {
	*x = KeyboardType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyboard_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardType) ProtoMessage() {}

func (x *KeyboardType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyboard_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardType.ProtoReflect.Descriptor instead.
func (*KeyboardType) Descriptor() ([]byte, []int) {
	return file_proto_keyboard_message_proto_rawDescGZIP(), []int{0}
}

func (x *KeyboardType) GetLayout() KeyboardType_KeyboardLayout {
	if x != nil {
		return x.Layout
	}
	return KeyboardType_UNKNOWN
}

func (x *KeyboardType) GetBacklit() bool {
	if x != nil {
		return x.Backlit
	}
	return false
}

var File_proto_keyboard_message_proto protoreflect.FileDescriptor

var file_proto_keyboard_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x22,
	0xb1, 0x01, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x44, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x74,
	0x22, 0x41, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x51, 0x57, 0x45, 0x52, 0x54, 0x59, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x51,
	0x57, 0x45, 0x52, 0x54, 0x5a, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x5a, 0x45, 0x52, 0x54,
	0x59, 0x10, 0x03, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x70, 0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_keyboard_message_proto_rawDescOnce sync.Once
	file_proto_keyboard_message_proto_rawDescData = file_proto_keyboard_message_proto_rawDesc
)

func file_proto_keyboard_message_proto_rawDescGZIP() []byte {
	file_proto_keyboard_message_proto_rawDescOnce.Do(func() {
		file_proto_keyboard_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_keyboard_message_proto_rawDescData)
	})
	return file_proto_keyboard_message_proto_rawDescData
}

var file_proto_keyboard_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_keyboard_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_keyboard_message_proto_goTypes = []any{
	(KeyboardType_KeyboardLayout)(0), // 0: process_manager.KeyboardType.KeyboardLayout
	(*KeyboardType)(nil),             // 1: process_manager.KeyboardType
}
var file_proto_keyboard_message_proto_depIdxs = []int32{
	0, // 0: process_manager.KeyboardType.layout:type_name -> process_manager.KeyboardType.KeyboardLayout
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_keyboard_message_proto_init() }
func file_proto_keyboard_message_proto_init() {
	if File_proto_keyboard_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_keyboard_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KeyboardType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_keyboard_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_keyboard_message_proto_goTypes,
		DependencyIndexes: file_proto_keyboard_message_proto_depIdxs,
		EnumInfos:         file_proto_keyboard_message_proto_enumTypes,
		MessageInfos:      file_proto_keyboard_message_proto_msgTypes,
	}.Build()
	File_proto_keyboard_message_proto = out.File
	file_proto_keyboard_message_proto_rawDesc = nil
	file_proto_keyboard_message_proto_goTypes = nil
	file_proto_keyboard_message_proto_depIdxs = nil
}
