// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: proto/laptop_service.proto

package psm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	LaptopService_CreateLaptop_FullMethodName = "/process_manager.LaptopService/CreateLaptop"
	LaptopService_FindLaptop_FullMethodName   = "/process_manager.LaptopService/FindLaptop"
	LaptopService_FilterLaptop_FullMethodName = "/process_manager.LaptopService/FilterLaptop"
)

// LaptopServiceClient is the client API for LaptopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LaptopServiceClient interface {
	CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLaptopResponse, error)
	FindLaptop(ctx context.Context, in *FindLaptopRequest, opts ...grpc.CallOption) (*FindLaptopResponse, error)
	FilterLaptop(ctx context.Context, in *FilterLaptopRequest, opts ...grpc.CallOption) (LaptopService_FilterLaptopClient, error)
}

type laptopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLaptopServiceClient(cc grpc.ClientConnInterface) LaptopServiceClient {
	return &laptopServiceClient{cc}
}

func (c *laptopServiceClient) CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLaptopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLaptopResponse)
	err := c.cc.Invoke(ctx, LaptopService_CreateLaptop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laptopServiceClient) FindLaptop(ctx context.Context, in *FindLaptopRequest, opts ...grpc.CallOption) (*FindLaptopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindLaptopResponse)
	err := c.cc.Invoke(ctx, LaptopService_FindLaptop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laptopServiceClient) FilterLaptop(ctx context.Context, in *FilterLaptopRequest, opts ...grpc.CallOption) (LaptopService_FilterLaptopClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LaptopService_ServiceDesc.Streams[0], LaptopService_FilterLaptop_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &laptopServiceFilterLaptopClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LaptopService_FilterLaptopClient interface {
	Recv() (*FilterLaptopResponse, error)
	grpc.ClientStream
}

type laptopServiceFilterLaptopClient struct {
	grpc.ClientStream
}

func (x *laptopServiceFilterLaptopClient) Recv() (*FilterLaptopResponse, error) {
	m := new(FilterLaptopResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LaptopServiceServer is the server API for LaptopService service.
// All implementations must embed UnimplementedLaptopServiceServer
// for forward compatibility
type LaptopServiceServer interface {
	CreateLaptop(context.Context, *CreateLaptopRequest) (*CreateLaptopResponse, error)
	FindLaptop(context.Context, *FindLaptopRequest) (*FindLaptopResponse, error)
	FilterLaptop(*FilterLaptopRequest, LaptopService_FilterLaptopServer) error
	mustEmbedUnimplementedLaptopServiceServer()
}

// UnimplementedLaptopServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLaptopServiceServer struct {
}

func (UnimplementedLaptopServiceServer) CreateLaptop(context.Context, *CreateLaptopRequest) (*CreateLaptopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLaptop not implemented")
}
func (UnimplementedLaptopServiceServer) FindLaptop(context.Context, *FindLaptopRequest) (*FindLaptopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLaptop not implemented")
}
func (UnimplementedLaptopServiceServer) FilterLaptop(*FilterLaptopRequest, LaptopService_FilterLaptopServer) error {
	return status.Errorf(codes.Unimplemented, "method FilterLaptop not implemented")
}
func (UnimplementedLaptopServiceServer) mustEmbedUnimplementedLaptopServiceServer() {}

// UnsafeLaptopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaptopServiceServer will
// result in compilation errors.
type UnsafeLaptopServiceServer interface {
	mustEmbedUnimplementedLaptopServiceServer()
}

func RegisterLaptopServiceServer(s grpc.ServiceRegistrar, srv LaptopServiceServer) {
	s.RegisterService(&LaptopService_ServiceDesc, srv)
}

func _LaptopService_CreateLaptop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLaptopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaptopServiceServer).CreateLaptop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaptopService_CreateLaptop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaptopServiceServer).CreateLaptop(ctx, req.(*CreateLaptopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaptopService_FindLaptop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLaptopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaptopServiceServer).FindLaptop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaptopService_FindLaptop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaptopServiceServer).FindLaptop(ctx, req.(*FindLaptopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaptopService_FilterLaptop_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FilterLaptopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LaptopServiceServer).FilterLaptop(m, &laptopServiceFilterLaptopServer{ServerStream: stream})
}

type LaptopService_FilterLaptopServer interface {
	Send(*FilterLaptopResponse) error
	grpc.ServerStream
}

type laptopServiceFilterLaptopServer struct {
	grpc.ServerStream
}

func (x *laptopServiceFilterLaptopServer) Send(m *FilterLaptopResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LaptopService_ServiceDesc is the grpc.ServiceDesc for LaptopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LaptopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "process_manager.LaptopService",
	HandlerType: (*LaptopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLaptop",
			Handler:    _LaptopService_CreateLaptop_Handler,
		},
		{
			MethodName: "FindLaptop",
			Handler:    _LaptopService_FindLaptop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FilterLaptop",
			Handler:       _LaptopService_FilterLaptop_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/laptop_service.proto",
}
